### PR TITLE
fix(scrolling): account for container scroll offsets when updating position of tips + improved tip scrolling

### PR DESCRIPTION
**Pull request by booleanbetrayal**
Fixes an issue when positioning tour-tips that are parented to a container which has been scrolled some offset. Also improved centering of tour-tip during automated scrolls.

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
@yhnavein - Let me know if you have any questions about this!

**Comment by yhnavein** [comment]
Hi @booleanbetrayal,

Thanks for PR, but, please take a look into example usage of the angular-tour in `/demo`. After your changes the demo page is broken :)

FYI: `grunt serve`

Cheers

**Comment by booleanbetrayal** [comment]
Sorry! Should be fixed now.

**Comment by yhnavein** [comment]
Thanks @booleanbetrayal

**Comment by booleanbetrayal** [comment]
:+1:

**Comment by booleanbetrayal** [comment]
Just caught a minor issue I introduced with the last commit. Sending a PR your way shortly.

**Pull request merged**
